"""资源站服务常量定义"""

RESOURCE_CONFIG_ROOT_KEY = "sites"

CONNECTION_SUCCESS_MESSAGE = "连接成功，API响应正常"
CONNECTION_FAILED_MESSAGE = "连接失败"
CONFIG_READ_ERROR_MESSAGE = "配置读取失败"
CONFIG_SAVE_ERROR_MESSAGE = "配置保存失败"
